name: CD - Terraform + Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Kubectl para Kind
        run: |
          kind create cluster --name dev --wait 60s
          kubectl cluster-info

      - name: Instalar Helm
        uses: azure/setup-helm@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Inicializar Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validar Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Aplicar Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Verificar recursos no cluster
        run: kubectl get all -n nginx-namespace
